#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case \`uname\` in
  *CYGWIN*|*MINGW*|*MSYS*) basedir=\`cygpath -w "$basedir"\`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../ospec/bin/ospec" "$@"
  ret=$?
else
  node  "$basedir/../ospec/bin/ospec" "$@"
  ret=$?
fi
exit $ret
