name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.task }}, node v${{ matrix.node_version }} on ${{ matrix.os }}
    strategy:
      matrix:
        task:
        - test-cli
        - test-api
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node_version:
        - 16
        - 18
        - 20
        - 22
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    - run: npm ci
    - run: npm run ${{ matrix.task }}
